### ISSUE TITLE
How to animate fragment transitions?

### ISSUE THREAD

**Issue by pavel-zlotarenchuk** [terrakok/Cicerone#102]
The description says the following:

Additional features
predefined navigator ready for setup transition animation

But I not find how make it. Please help me

**Comment by adolgiy** [comment]
You should look for [SupportAppNavigator#setupFragmentTransaction](https://github.com/terrakok/Cicerone/blob/master/library/src/main/java/ru/terrakok/cicerone/android/support/SupportAppNavigator.java#L217)
