### ISSUE TITLE
NullPointerException for binding views with 'Butterknife'

### ISSUE THREAD

**Issue by SWRHARD** [terrakok/Cicerone#103]
Okay, I have 2 screens: A, B;
1. 'A' screen opening by BottomNavigationView;
2. 'B' screen opening inside screen 'A';

My steps:

1. I open 'A' screen by clicking at item of BottomNavigationView -> **router.newRootScreen()**

2. I open 'B' screen by clicking button inside 'A' screen -> **router.replaceScreen()**

3. I clicks at the same item of BottomNavigationView like at 1st step and get NPE for views;
I used butterknife for binding, cant understand what happens :(
If i use back button from 'B' to 'A' screen, app works great.

**Comment by terrakok** [comment]
Can you give me more information, stacktrace or sample code? With patch to demo app, for example

**Comment by terrakok** [comment]
outdated
