### ISSUE TITLE
FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by nkpodolyan** [terrakok/Cicerone#104]
Here is a stack trace:

'''
java.lang.IllegalStateException: FragmentManager is already executing transactions
        at androidx.fragment.app.FragmentManagerImpl.ensureExecReady(FragmentManagerImpl.java:1659)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1720)
        at androidx.fragment.app.FragmentManagerImpl.executePendingTransactions(FragmentManagerImpl.java:183)
        at ru.terrakok.cicerone.android.support.SupportAppNavigator.applyCommands(SupportAppNavigator.java:44)
        at ru.terrakok.cicerone.CommandBuffer.executeCommands(CommandBuffer.java:42)
        at ru.terrakok.cicerone.CommandBuffer.setNavigator(CommandBuffer.java:25)
        at my.app.MainFragment.onResume(MainFragment.kt:60)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2644)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:921)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1237)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1302)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2075)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1865)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1820)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1726)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
'''

This happens after I use cicerone navigator to replace fragments in activity (navigator uses support fragment manager). Inside target fragment (1) inside onViewCreated() callback I ask cicerone to add child fragment and (2) set navigator to cicerone navigation holder (navigator uses child fragment manager) inside onResume() callback. 

CommandBuffer.setNavigator() causes executing pending transactions and application crashes with the provided exception.

Please advice how to overcome this issue

**Comment by hborelligt** [comment]
Same issue.

**Comment by igozhenko** [comment]
Same problem 
`

android.support.v4.app.FragmentManagerImpl.ensureExecReady + 2207 (FragmentManager.java:2207)
--
  | android.support.v4.app.FragmentManagerImpl.execPendingActions + 2267 (FragmentManager.java:2267)
  | android.support.v4.app.FragmentManagerImpl.executePendingTransactions + 814 (FragmentManager.java:814)
  | ru.terrakok.cicerone.android.support.SupportAppNavigator.applyCommands + 44 (SupportAppNavigator.java:44)
  | ru.terrakok.cicerone.CommandBuffer.executeCommands + 42 (CommandBuffer.java:42)
  | ru.terrakok.cicerone.BaseRouter.executeCommands + 30 (BaseRouter.java:30)
  | ru.terrakok.cicerone.Router.replaceScreen + 55 (Router.java:55)
  | com.authenteq.android.flow.ui.onboarding.liveness.LivenessMvpPresenter.onFirstViewAttach + 50 (LivenessMvpPresenter.java:50)
  | com.arellomobile.mvp.MvpPresenter.attachView + 49 (MvpPresenter.java:49)
  | com.arellomobile.mvp.MvpDelegate.onAttach + 121 (MvpDelegate.java:121)
  | com.arellomobile.mvp.MvpAppCompatFragment.onStart + 32 (MvpAppCompatFragment.java:32)
  | android.support.v4.app.Fragment.performStart + 2477 (Fragment.java:2477)
  | android.support.v4.app.FragmentManagerImpl.moveToState + 1494 (FragmentManager.java:1494)
  | android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState + 1784 (FragmentManager.java:1784)
  | android.support.v4.app.FragmentManagerImpl.moveToState + 1852 (FragmentManager.java:1852)
  | android.support.v4.app.BackStackRecord.executeOps + 802 (BackStackRecord.java:802)
  | android.support.v4.app.FragmentManagerImpl.executeOps + 2625 (FragmentManager.java:2625)
  | android.support.v4.app.FragmentManagerImpl.executeOpsTogether + 2411 (FragmentManager.java:2411)
  | android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute + 2366 (FragmentManager.java:2366)
  | android.support.v4.app.FragmentManagerImpl.execPendingActions + 2273 (FragmentManager.java:2273)
  | android.support.v4.app.FragmentManagerImpl$1.run + 733 (FragmentManager.java:733)
  | android.os.Handler.handleCallback + 873 (Handler.java:873)
  | android.os.Handler.dispatchMessage + 99 (Handler.java:99)
  | android.os.Looper.loop + 193 (Looper.java:193)
  | android.app.ActivityThread.main + 6863 (ActivityThread.java:6863)
  | java.lang.reflect.Method.invoke (Method.java)
  | com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 537 (RuntimeInit.java:537)
  | com.android.internal.os.ZygoteInit.main + 858 (ZygoteInit.java:858)

`

**Comment by AmirVagapov** [comment]
Same issue

**Comment by AleksandrTabolin** [comment]
Same issue

**Comment by AleksandrTabolin** [comment]
fast and dirty hack
```
    private val handler: Handler = Handler(Looper.getMainLooper())

    override fun applyCommands(commands: Array<Command>) {
        try {
            fragmentManager.executePendingTransactions()
            //copy stack before apply commands
            copyStackToLocal()
            for (command in commands) {
                applyCommand(command)
            }
        } catch (error: IllegalStateException) {
            Timber.w(error)
            handler.postDelayed({
                applyCommands(commands)
            }, 100)
        }
    }
```

**Comment by taraskreknin** [comment]
From [Readme](https://github.com/terrakok/Cicerone#how-it-works):
> Attention: Use onResumeFragments() with FragmentActivity
That fixed the problem in my case.

**Comment by TooLazyy** [comment]
> From [Readme](https://github.com/terrakok/Cicerone#how-it-works):
> 
> > Attention: Use onResumeFragments() with FragmentActivity
> 
> That fixed the problem in my case.

Not helped in case we start a new fragment from `onActivityCreated` of a first one.
What can help - do your `router.navigateTo` or whateve in `Handler().post {}` or wrap `fragmentManager.executePendingTransactions()` in Navigator with **try catch**

**Comment by sankarsana** [comment]
I faced the same problem.

**Comment by terrakok** [comment]
In new version of library you can implement won error handling: https://github.com/terrakok/Cicerone/releases/tag/v5.1.0

**Comment by terrakok** [comment]
But this issue says that you want to use fragment manager when system doesn't ready for this. I recommend fix it in your application. Maybe you start navigation in `onCreate` callback instead `onResume` or something else

**Comment by andre-sonect** [comment]
@terrakok I have started the navigation in `onResume` but still happens

**Comment by dracula6322** [comment]
Try using ChildFragmentManager instead of FragmentManager

**Comment by android-design** [comment]
> @terrakok I have started the navigation in `onResume` but still happens

in the end, how to solve this problem?

**Comment by terrakok** [comment]
Please, show me reproducer and I will fix it. You can create patch in demo app.

**Comment by android-design** [comment]
> Please, show me reproducer and I will fix it. You can create patch in demo app.
Here's the patch, thank you!

[Test_error_when_call_cicerone_library_.patch.zip](https://github.com/terrakok/Cicerone/files/5977730/Test_error_when_call_cicerone_library_.patch.zip)

**Comment by terrakok** [comment]
You have to change your code to:
```kotlin
override fun onResume() {
  super.onResume()
  if (number == 1) {
    presenter.test()
  }
}
```
Otherwise you call forward navigation recursively.

<img width="463" alt="изображение" src="https://user-images.githubusercontent.com/3532155/107885924-0dff6a00-6f0e-11eb-842a-4bf681337406.png">

**Comment by terrakok** [comment]
So, I don't know reproducer for this issue.  
If you set the `navigator` to the holder in `onResumeFragments` lifecycle callback than you can safely call navigation commands inside fragments.
