### ISSUE TITLE
How to send back the result

### ISSUE THREAD

**Issue by mancj** [terrakok/Cicerone#105]
Thank you for a good library! 

You wrote that returning of the result is removed from the library, because this problem is not related to the navigation. 
But the problem remains, it is not clear which approach to use for this, how to return back the data to the previous activity/fragment?

**Comment by adolgiy** [comment]
Here is the answer - [PhotoSelection.java](https://github.com/terrakok/Cicerone/tree/master/sample/src/main/java/ru/terrakok/cicerone/sample/mvp/animation)

**Comment by terrakok** [comment]
You should use common shared state between screens.  When one screen change this state than other listen changes and handles it.
