### ISSUE TITLE
DialogFragment support?

### ISSUE THREAD

**Issue by Spellbit** [terrakok/Cicerone#106]
Greteengs! It would be great to have DialogFragment support out of the box. Its a pretty much common case and for now we have to subclass Navigator and implement it manually.

**Comment by mathemandy** [comment]
@Spellbit  do you have a workaround, i currently have a need for it ?

**Comment by Spellbit** [comment]
> @Spellbit do you have a workaround, i currently have a need for it ?
```
For the moment i have a very quick and crude solution. For example here is my fragmentForward of Navigator:

    protected fun fragmentForward(command: Forward) {
        val screen = command.screen as SupportAppScreen
        val fragment = createFragment(screen)

        val fragmentTransaction = fragmentManager.beginTransaction()
        setupFragmentTransaction(
                command,
                fragmentManager.findFragmentById(containerId),
                fragment,
                fragmentTransaction
        )

        fragmentTransaction.addToBackStack(screen.screenKey)

        if (fragment is android.support.v4.app.DialogFragment) {
            fragment.show(fragmentTransaction, screen.screenKey)
        } else {
            fragmentTransaction
                    .replace(containerId, fragment)
                    .commit()
        }
        localStackCopy!!.add(screen.screenKey)
    }
```
As you can see, there is a check if our fragment is an instance of DialogFragment and if it is - call of the show function. fragmentReplace is similar. Unfortunately its a very crude solution cause need to call dismiss to close DialogFragment and as a consequence you cant navigate back with router. To solve this we need to deal with stack in DialogFragment case somehow.  When i got some time for it - maybe i will make a more decent implementation but for now i just call dismiss from view.

**Comment by terrakok** [comment]
Hello! My opinion is Dialogs are not navigation screens! Because android puts dialogs not in container but in system window. What happens if you want replace dialog to fragment? Or set dialog as root screen? There are a lot of corner cases with dialogs. I don't know good common solution for managing dialogs at the moment :)

**Comment by nikialeksey** [comment]
Jetpack navigation has this feature [since 2.1.0](https://developer.android.com/jetpack/androidx/releases/navigation#2.1.0)
