### ISSUE TITLE
NPE if overriden errorWhileCreatingScreen method doesn't throw an exception

### ISSUE THREAD

**Issue by zwieback** [terrakok/Cicerone#108]
If I will override [errorWhileCreatingScreen](https://github.com/terrakok/Cicerone/commit/47f5197f9029d3372adfc21e10a9575a75a7967a#diff-16f5e6effc459238e0958e8bcb8dac88R240) method in the `SupportFragmentNavigator`'s subclass so that this method will not throw an exception, then an NPE will be thrown at the `FragmentTransaction.commit` method [in this place](https://github.com/terrakok/Cicerone/commit/47f5197f9029d3372adfc21e10a9575a75a7967a#diff-16f5e6effc459238e0958e8bcb8dac88R120) because [this null check](https://github.com/terrakok/Cicerone/commit/47f5197f9029d3372adfc21e10a9575a75a7967a#diff-16f5e6effc459238e0958e8bcb8dac88L107) was deleted.

I suggest returning the null check after creating the fragment.

**Comment by terrakok** [comment]
Good point! #111

**Comment by zwieback** [comment]
Thanks, @terrakok. You rock!
