### ISSUE TITLE
Searching for replacement for setResultListener method 

### ISSUE THREAD

**Issue by Turbozanik** [terrakok/Cicerone#123]
In cicerone version 2.1.0 there was a method setResultListener, that we used to do the same behavior as setTargetFragment.
Now we have updated to 5.1.1 due to androidx migration, and we are having issues with the new logic.

How can we fix this?

![Снимок](https://user-images.githubusercontent.com/7550948/91030667-3154f680-e608-11ea-80cf-992aa2f6e4c4.PNG)

**Comment by terrakok** [comment]
Added in https://github.com/terrakok/Cicerone/releases/tag/v6.1
