### ISSUE TITLE
Can't be used in Java projects?

### ISSUE THREAD

**Issue by mindvv0rk** [terrakok/Cicerone#127]
I use ru.terrakok.cicerone:cicerone:5.1.1. When i was wanted to use setResult for Fragment, i was try to migrate to 6.1. But in version 6.1 FragmentScreen and ActivityScreen has constructor parameter kotlin.jvm.functions.Function1. 
Am i right that i can not use 6.1 without Kotlin compiler?

**Comment by terrakok** [comment]
At the moment new version of library doesn't interop with Java.  
Reason is Kotlin is new default for android applications. And now it is more convenient to understand and support library (for me and for external contributors).  
But I will be very happy if you add interoperability annotations for using with Java.

**Comment by terrakok** [comment]
Released in version 6.4
