### ISSUE TITLE
ResultWire issue

### ISSUE THREAD

**Issue by MonStar1** [terrakok/Cicerone#130]
Looks like WeakReference lost the link to the listener. It happens randomly. I caught it in sample project at least three times (watch attached video with last one case). I know it is hard to understand from GIF what happen, better try to make the GIF slower
I've added logs and you can see the listener is null inside WeakReference.
It happens very often in my production project

<img width="1370" alt="issue_cicerone" src="https://user-images.githubusercontent.com/5097847/99381004-bf750c00-28db-11eb-8522-a7b515fe7743.png">

![ezgif com-gif-maker](https://user-images.githubusercontent.com/5097847/99380991-ba17c180-28db-11eb-82d8-660f0a01368a.gif)

**Comment by MonStar1** [comment]
@terrakok you can contact me by email: mazaxict1@gmail.com

**Comment by amatkivskiy** [comment]
Faced the same issue. 😞

**Comment by terrakok** [comment]
Redundant listeners are cleared after sendResult. It is intentional behavior 
https://github.com/terrakok/Cicerone/blob/master/library/src/main/kotlin/com/github/terrakok/cicerone/BaseRouter.kt#L35

**Comment by amatkivskiy** [comment]
@terrakok Yeah, sorry for the confusion. Here is the code for logging: 
```
internal class ResultWire {

    fun sendResult(key: String, data: Any) {
        println("sendResult key '$key', data: $data")
        printListeners()
        listeners.remove(key)?.get()?.let { listener ->
            println("found listener '$listener'")
            listener.onResult(data)
        }
    }

    fun printListeners() {
        println("printing listeners")
        listeners.onEach {
            println("listener: ${it.key}=${it.value.get()}")
        }
    }

    fun flush() {
        listeners.entries
            .filter { it.value.get() == null }
            .forEach {
                println("removing '${it.key}'")
                listeners.remove(it.key)
            }
    }
}
```

**Comment by amatkivskiy** [comment]
@terrakok here is code that triggers screen: 
```
router.setResultListener("terms_accepted") { data ->
	areTermsAndConditionsAccepted = data as Boolean
}
router.navigateTo(Screens.termsAndConditions)
```
here is `termsAndConditions` screen:
```
router.sendResult("terms_accepted", true)
router.exit()
```

**Comment by terrakok** [comment]
Oh! I've understood! ResultWire saves weak ref to lambda so it is only one ref to this callback. And, of course,  GC can to flush it.

**Comment by terrakok** [comment]
If I save strong link to callback it will be leaked.
So, we can save key-callback pairs to stack and flush all newest links when process some result

**Comment by terrakok** [comment]
But that doesn't get rid of the situation when viewmodel subscribed on result and never received them. And it will be leaked via strong reference on callback when user leaved screen  :(

**Comment by amatkivskiy** [comment]
@terrakok yeah, but maybe we can link callback to a screen that created it? so when you leave the screen that created listener it is clear (but I might be saying some stupid stuff 😄 )

**Comment by terrakok** [comment]
No. Screen is factory for real views in system (e.g. for fragment). You can use same Screen for several views in chain.

**Comment by terrakok** [comment]
But it is good direction for thought.
May be it is possible associate listeners with current backstack

**Comment by amatkivskiy** [comment]
@terrakok maybe just a quick (and dirty) fix: what if I remove a listener in the callback body of the listener?

```
router.setResultListener("terms_accepted") { data ->
     router.removeLisener("terms_accepted")
}
```

**Comment by terrakok** [comment]
Quick fix: save link to callback inside viewmodel too

**Comment by terrakok** [comment]
I've added ResultListenerHandler for cleaning link on viewmodel:
https://github.com/terrakok/Cicerone/blob/master/sample/src/main/java/com/github/terrakok/cicerone/sample/mvp/animation/profile/ProfilePresenter.kt#L30

**Comment by amatkivskiy** [comment]
@terrakok Thanks, I will try it today or tomorrow. Thanks for your quick help 👍

**Comment by amatkivskiy** [comment]
Hi @terrakok, seems that your approach with listener works for me. Thanks for helping 👍 🥇
