### ISSUE TITLE
Question: How to close child navigation graps (chains) using Cicerone? 

### ISSUE THREAD

**Issue by amatkivskiy** [terrakok/Cicerone#134]
Hi @terrakok ,

I am using your library for the first time, so I am nor sure how to handle all the scenarios properly. 

Right now I am struggling with a scenario where I want to open a child graph, something like this: 
Screens: **A**, **B**, **C** (where **B** and **C** are child screens)
`A  -> B -> C`

and then when the user clicks on the button on **C** I want to close **B** and **C** screens and send the result to screen **A**. I am OK with sending the result but I am wondering how to close **B** and **C** screens properly. 

Initially, I thought that this can be done easily using `router.newChain()` method (in my case `router.newChain(Screens.B)`). 
After the user clicks on the button on the screen  **C** I am doing this: `router.finishChain()`. 

The issue is that `router.finishChain()` closes all screens. 

Can you please clarify if this is a designed behavior or I am doing something wrong?

**Comment by terrakok** [comment]
`newChain` adds chain of screens to current stack. You can call `backTo(A)` in C.
Or you can create truly child graph in inner container with independent stack (fragment with inner router and navigator).

**Comment by amatkivskiy** [comment]
@terrakok What about screen arguments when calling backTo() ? 

Should I pass the same arguments as I did when created initial **A** screen? Or is doesn't matter and just call backTo(**A**)?

**Comment by terrakok** [comment]
It doesn't matter

**Comment by amatkivskiy** [comment]
@terrakok  One small remark about `backTo(A)`: for `backTo()` to work properly your `FragmentScreen()`  should also specify `key` parameter.  Like this: 

```
fun FragmentA() = FragmentScreen(key = "FragmentA") {
        FragmentA.getNewInstance()
}
```
Otherwise `backTo()` won't work at all 😞 

PS: Maybe this can be stated somewhere in README or javadocs.

**Comment by terrakok** [comment]
Yes, you are right. I have forgot about it 👍
