### ISSUE TITLE
Two navigators in one activity

### ISSUE THREAD

**Issue by lectricas** [terrakok/Cicerone#14]
Hi again. I have a BaseActivity and I want to put both fragment and Activity navigators in it, because I want to open fragment/activity from any place/screen of my app. Is this possible?
Suppose I want to navigate to fragment or to other activity from currentActivity.

```
SampleApplication.INSTANCE.getNavigatorHolder().setNavigator(fragment);
SampleApplication.INSTANCE.getNavigatorHolder().setNavigator(activity); // addNavigator()?
```

**Comment by Jeevuz** [comment]
Hi! I think yes, its possible. But it will cause the Navigator in the BaseActivity to know about all transitions (activities and fragments). And such a big navigator can be a downside of this idea. But logically this will be the same as in sample app - when your activity dies, the navigator implemented in BaseActivity will be removed from the NavigationHolder, and exactly the same instance of navigator (from BaseActivity) will be added to it when new Activity appears.

**Comment by terrakok** [comment]
Hi, good question! 
We need to remember that Router has only one active Navigator in a time. 
So you can do what you need in this way:
In the BaseActivity put Navigator instance that implements all activity  transitions. But for all fragment transitions it will call a subactivity's method. Activity that extends the base one will override this method to resolve fragment transitions.

**Comment by lectricas** [comment]
@terrakok 
still didn't get it. In order to call fragmentNavigator method, we need to attach it to activity lifecycler by 
```
    @Override
    protected void onResume() {
        super.onResume();
        SampleApplication.INSTANCE.getNavigatorHolder().setNavigator(navigator);
    }
```
Ok, we did that and now we want to startNewActivity.
How we should change the navigator?

@Jeevuz I suppose that having all screen navigation in one place would be awesome. Wanna see it in practice.

**Comment by Jeevuz** [comment]
If you want one *big navigator* so put it in BaseActivity. In this navigator you will put all your navigation logic both for activities and fragments transitions (eg. if this is sceen1 open activity1, if screen2 replace fragment to fragment2). Then you will add/remove this navigator in onResume/onPause of the BaseActivity. And that's it. You have our big navigator knowing all transitions of your app. 

But if you want to *divide your navigation*, as @terrakok mentioned, so your BaseActivity navigator's applyCommand will call subactivity's method if it don't know how to handle some screens:
```java
public class BaseActivity {

    ...

    @Override
    protected void onResume() {
        super.onResume();
        SampleApplication.INSTANCE.getNavigatorHolder().setNavigator(navigator);
    }

    @Override
    protected void onPause() {
        super.onPause();
        SampleApplication.INSTANCE.getNavigatorHolder().removeNavigator();
    }

    ...

    public class BaseNavigator implements Navigator {
    private FragmentManager fragmentManager;
    private int containerId;

    public FragmentNavigator(FragmentManager fragmentManager, int containerId) {
        this.fragmentManager = fragmentManager;
        this.containerId = containerId;
    }

    @Override
    public void applyCommand(Command command) {
        if (command instanceof Forward) {
            Forward forward = (Forward) command;
            if (SCREEN_NAME_ACTIVITY_1.equals(forward.getScreenKey())) {
                // start your activity
            } else {
                // all fragment transitions will be handled by subactivity
                applyCommandInternal(command);
            }
        } else ...

        ... 
    }
    
    ...

    protected void applyCommandInternal(Command command) {
        // Nothing. Override in subactivity to perform fragment transitions.
    }
}
```
I hope you get the idea. 

And I want to mention, that in both this cases you will need to implement your own Navigator that can do activity and fragment transitions at the same time.
