### ISSUE TITLE
error with Creator ActivityScreen

### ISSUE THREAD

**Issue by HotsHom** [terrakok/Cicerone#147]
Hi, I can't figure out what the problem is. I am trying to indicate the screen from ActivityScreen, But this error occurs 
`Type mismatch.
Required:
Creator<Context, Intent>
Found:
() → Intent`

**object class Screens**
```
import com.csproject.rflex.app.App
import com.csproject.rflex.presentation.launch.LaunchActivity
import com.github.terrakok.cicerone.androidx.ActivityScreen

object Screens {

    fun launch() = ActivityScreen {
        LaunchActivity.newIntent(App)
    }

}
```

**LaunchActivity**
```
class LaunchActivity: ABaseActivity(), ILaunchView {

    companion object{
        fun newIntent(context: Context) = Intent(context, LaunchActivity::class.java)
    }
....
```
Can you please figure out what the problem is

**Comment by AndSky90** [comment]
>  LaunchActivity.newIntent(App)

try to replace with "LaunchActivity.newIntent(it)"
