### ISSUE TITLE
How to use Cicerone in sigleActivity multimodule app?

### ISSUE THREAD

**Issue by NurseyitTursunkulov** [terrakok/Cicerone#148]
in multimodule app we navigate to another module with startactivity(), but is it possible to have single activity and use your library for navigation?

**Comment by terrakok** [comment]
Yes. You have to implement your modules as Fragments and show them via transactions

**Comment by NurseyitTursunkulov** [comment]
is there any samples ?

**Comment by terrakok** [comment]
I don't know open sourced samples but I did it some time ago for closed app.  
Main idea is Coordinator abstraction. It is interface with navigation methods which is implemented in main app module via Cicerone calls
