### ISSUE TITLE
Migration to mavenCentral

### ISSUE THREAD

**Issue by jolaf** [terrakok/Cicerone#154]
For now, Cicerone is available from jCenter repository, which is being deprecated:
http://developer.android.com/r/tools/jcenter-end-of-service

It would be nice to have Cicerone available from mavenCentral() to be used further.

**Comment by TanyaYu** [comment]
@jolaf , When I switched my Cicerone dependency from `implementation "ru.terrakok.cicerone:cicerone:X.X.X"` to `implementation "com.github.terrakok:cicerone:X.X.X"` , the issue has been resolved for me.

**Comment by jolaf** [comment]
Yeah, worked perfectly for me, thanks!
