### ISSUE TITLE
The best way to pass arguments to a fragment.

### ISSUE THREAD

**Issue by lectricas** [terrakok/Cicerone#16]
So, guys, you have:
```
private Navigator navigator = new SupportFragmentNavigator(getSupportFragmentManager(), R.id.main_container) {
        @Override
        protected Fragment createFragment(String screenKey, Object data) {
            return SampleFragment.getNewInstance((int) data);
        }
}
```

```
public static SampleFragment getNewInstance(int number) {
        SampleFragment fragment = new SampleFragment();

        Bundle args = new Bundle();
        args.putInt(EXTRA_NUMBER, number);
        fragment.setArguments(args);

        return fragment;
    }
```

and then you execute it with a pretty simple command: 

`navigator.applyCommand(new Replace(Screens.SAMPLE_SCREEN, 1));`

But what if I have more than argument?
Lets say 5 of them?
I can create a helper class with this 5 fields, or pass bundle every time I need to open a fragment.
Maybe you have a better way?

**Comment by terrakok** [comment]
Yes, we're doing the same.
We create InitParams class nested in Presenter to pass parameters.

**Comment by lectricas** [comment]
thanks
