### ISSUE TITLE
Open activity from fragment

### ISSUE THREAD

**Issue by harcoPro** [terrakok/Cicerone#18]
How i can open new activity from fragment? I use SupportFragmentNavigator which adding to router in activity.

**Comment by terrakok** [comment]
SupportFragmentNavigator is example Navigator for simple fragment navigations.
For start activity you can override it and add code like this:
```java
@Override
public void applyCommand(Command command) {
 if (command instanceof Forward) {
  Forward fwd = (Forward) command;
  if (fwd.getScreenKey().equals("Your activity screen key")) {
   startActivity(...);
  } else {
   super(command);
  }
 }
}
```
Usualy, i create custom Navigator for real project.

**Comment by harcoPro** [comment]
Ok, thanks!
