### ISSUE TITLE
Need ability to interact with currently visible fragment

### ISSUE THREAD

**Issue by geared554** [terrakok/Cicerone#21]
It would be nice to just take fragment from top of chain.
For example
```
MyFragment fragment = cicerone.getTopFragment();
fragment.foo();
```

**Comment by terrakok** [comment]
It's not correct!
1) Your application can contain several active fragments at the same time!
2) Cicerone is not tied to fragments.
3) The navigation task is switching between screens, but not providing access to them.

**Comment by geared554** [comment]
Ok, I see. My mistake. I really forgot about first case provided by you when there's can be more than one visible fragment.
