### ISSUE TITLE
I think it would be better to add navigation animations

### ISSUE THREAD

**Issue by wlianghe00** [terrakok/Cicerone#30]

**Comment by terrakok** [comment]
Transitions' animation is the responsibility of the navigator.
Adding animations to predefined navigators is a good idea, but we need to figure out how to do it nicely and conveniently.
I propose to discuss it.

**Comment by terrakok** [comment]
Latest release (2.0.0) contains transition animation setup

**Comment by terrakok** [comment]
![](https://habrastorage.org/web/a63/881/7f8/a638817f8bba49daacc4fa427987fabb.gif)

**Comment by Jeevuz** [comment]
I think we can close this disscussion :)
