### ISSUE TITLE
Do not call executePendingTransactions() in backToRoot() if already on root (backstack empty)

### ISSUE THREAD

**Issue by Jeevuz** [terrakok/Cicerone#32]

**Comment by Jeevuz** [comment]
Also, seems it can cause the promlems when calling newRoot few times. We need to try popBackStackImmediate(null, POP_BACK_STACK_INCLUSIVE)...

**Comment by Jeevuz** [comment]
We can just call ```fragmentManager.popBackStackImmediate(null, FragmentManager.POP_BACK_STACK_INCLUSIVE);```. 
It will pop all backstack immediately.

**Comment by terrakok** [comment]
done!
