### ISSUE TITLE
How to transfer data with a command exit()

### ISSUE THREAD

**Issue by volkdown** [terrakok/Cicerone#40]
Hello! I need to transfer the data to the previous activity screen, because the current screen was launched with the command onActivityScreen. How can i do this?  If for example the command navigateTo allows me to do this, then exit() not have an object parameter for data transfer. Thanks in advance for the answer.

**Comment by Jeevuz** [comment]
Last version has a feature to return result. 
Call router.exitWithResult(RESULT_CODE, photoRes) and don't forget to subscribe/unsubscribe on the parent screen with router.setResultListener/removeResultListener.
See [sample's animation folder](https://github.com/terrakok/Cicerone/tree/develop/sample/src/main/java/ru/terrakok/cicerone/sample/mvp/animation)
