### ISSUE TITLE
More documentation please!

### ISSUE THREAD

**Issue by amitav13** [terrakok/Cicerone#43]
Hi, I've just started using this library and am finding it hard to see what the implementations of Command, Navigator, etc are. There's no API spec that I can find short of crawling through the source myself. 

A javadoc would be helpful. Thanks!

**Comment by terrakok** [comment]
Hmmm! It's very strange because library has javadocs

**Comment by amitav13** [comment]
It is well documented yes, but I was hoping for a hosted version
online

On August 16, 2017 at 9:23 PM, Konstantin
(notifications@github.com) wrote:

Hmmm! It's very strange because library has javadocs

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
( https://github.com/terrakok/Cicerone/issues/43#issuecomment-322816608 )
, or mute the thread

**Comment by Jeevuz** [comment]
This is nice proposal, thank you. But for such a small, focused library hosted javadocs is not necessary, IMHO. The source code is already self-explaining, plus we have javadocs for all public methods.

**Comment by amitav13** [comment]
If you'd still be interested, here's a site that can host them for free: https://www.javadoc.io/
