### ISSUE TITLE
Make activity class variable accessible for AppNavigator's subclasses

### ISSUE THREAD

**Issue by nedomovnyvlad** [terrakok/Cicerone#44]
I want to implement my navigator in separate class to make Activity's code look clearer. I need activity instance for createActivityIntent method. But activity class variable in AppNavigator is private. So i think it would be better to make it protected because now I have to declare another activity variable for my class and it looks really bad.

**Comment by Jeevuz** [comment]
To create an Intent you need context, not activity. So one of possibilities I see is to add the context parameter to the method createActivityIntent.

**Comment by nedomovnyvlad** [comment]
I agree, context as a parameter would be enough for my case
