### ISSUE TITLE
Using popBackStackImmediate() to replace the fragment

### ISSUE THREAD

**Issue by akotsuba** [terrakok/Cicerone#46]
Hi, thanks for the library!

Now I'm trying to use it in my current project, and I've faced the UI 'blink' artifact while replacing the fragments using the _SupportFragmentNavigator_ class provided by the library. So, the issue is:

1) navigate to the fragment **A**. The keyboard should appear here, so the appropriate code is added in the _onViewCreated_ method.
2) navigate to the fragment **B** (with the _navigateTo_ method). 
3) navigate to the fragment **C**. When the back button is pressed, A fragment should be shown, and U use the _replaceScreen_ method 

The blink happens because onViewCreated method is called while replacing B with C, and the keyboard tries to be shown for a moment.

Do you have any recommendations how to handle this situation?

**Comment by Jeevuz** [comment]
Hi! Sorry for the delay.

What you describes is the normal behavior while working with the Fragment's backstack. To replace fragment in the screens chain we need to call popBackStack and then add the new fragment in the backstack. There is no way to just replace backstack entry.

So all I can suggest to you is to move keyboard-showing method to the onResume and maybe add some delay. I think it will allow to replace fragment before keyboard will show itself.

If you already found better solution, let me know!

**Comment by AleksandrTabolin** [comment]
Hi!

```
fragmentManager.popBackStack(null, FragmentManager.POP_BACK_STACK_INCLUSIVE)
fragmentManager.beginTransaction()
                    .replace(containerId, fragment)
                    .commit()
fragmentManager.executePendingTransactions()
```

Custom 'NewRoot' command and implementation like this should help with this problem
Backstack will be changed at once without 'blinking'

**Comment by akotsuba** [comment]
Thanks for the answers! I think this one can be closed :) Yes, I use popBackStack as a result (sorry for the delay also)
