### ISSUE TITLE
Get 'transitionData' on new Activity

### ISSUE THREAD

**Issue by pablodeafsapps** [terrakok/Cicerone#48]
I happen to have the following line in my code, which invokes an `Activity` and passing a Map as argument:
`router?.navigateTo(RssFeedActivity.TAG, dataMap)`

My question is how to retrieve that data once the new `Activity` is running (similar to what, for instance,  `getIntent().geStringExtra("myStringKey")` does when simply using "plain" Android).

**Comment by Jeevuz** [comment]
Hi! 
Take a look at the `createActivityIntent(String screenKey, Object data)`. 
Here you have your data and this is your responsibility to put it into the Intent you are creating.

**Comment by pablodeafsapps** [comment]
Hi again,
I did not quite understand your recommendation, so I ended up doing the following in my code:
```
private val navigator: Navigator? by lazy {
        object : Navigator {
            override fun applyCommand(command: Command) {
                if (command is Forward) {
                    forward(command)
                }
            }
            private fun forward(command: Forward) {
                val data = (command.transitionData as Map<*, *>).filter { it.value == true }
                when (command.screenKey) {
                    RssFeedActivity.TAG -> startActivity(Intent(this@SportsListActivity, RssFeedActivity::class.java)
                            .putExtra("data", data as HashMap))
                    else -> Log.e("Cicerone", "Unknown screen: " + command.screenKey)
                }
            }
        }
    }
```

And in the receiver 'Activity':
```
override fun onResume() {
        super.onResume()
        presenter?.onViewCreated(intent.getSerializableExtra("data")?.let { it as HashMap<*, *> })
    }
```

Although it works, I would like to know whether this is the most appropriate way when using 'Cicerone'. Specifically, I do not like this approach since it requires doing a couple of explicit casts (as HashMap<*, *>, for instance), which I believe it is not a good practice. 

Could you please drop me your thoughts?! Thanks and regards.

**Comment by Jeevuz** [comment]
Hm. I think you should see the sample and predefined navigators. 
Regarding the data passing usually we create the Params class in the Presenter to hold all the data passing to the screen. Then create it when do the navigation, and cast the Object data to Params in the navigator. Then pass it from screen (eg. fragment) to the Presenter.

**Comment by Jeevuz** [comment]
If you have no more questions i think we can close this issue.
