### ISSUE TITLE
Return data on router.backTo(...)

### ISSUE THREAD

**Issue by ruha9005** [terrakok/Cicerone#53]
`router.navigateTo(EXTRA_NEXT_SCREEN, new Object())` is a great feature and I'm using it in my projects, but sometimes I need to return some data to previous step/fragment, for example, when I need to return token after phone confirm.
It would be great if I can use something like `router.backTo(EXTRA_PREVIOUS_SCREEN, new Object())` inside Cicerone routers logic and without necessity of injecting additional interactors to presenters.

**Comment by terrakok** [comment]
You can do it with in-memory observable model.

**Comment by Jeevuz** [comment]
See reasoning in the comments of the #47
