### ISSUE TITLE
Passing result through multiple activities

### ISSUE THREAD

**Issue by AlexisQapa** [terrakok/Cicerone#62]
Hi, 

Would this lib allow a result to be passed across multiple activities like :
A need result
D produce result
But B is finished or destroyed by android

A -> B (destroyed) -> C -> D

maybe a command like 
BackToWithResult(screen, result)

**Comment by heweidev** [comment]
Cicerone call the ResultListener by requestCode, so if you subcribe the listener in A and set result in D with the same requestCode, I think it will work

**Comment by terrakok** [comment]
New version of Cicerone is here! 🔥   
Now result transferring is out of library logic.
