### ISSUE TITLE
setupFragmentTransactionAnimation is not called in child fragment

### ISSUE THREAD

**Issue by yurimachioni** [terrakok/Cicerone#63]
First of all, nice library. It's been helping me a lot.
I'm having a problem in a setup similar to the BottomNavigationActivity of the sample.
I want to have a slide animation when navigating inside a tab (opening forwardFragments) and no animation or some other animation when I switch tabs. The problem is: when I switch tabs, the parent fragment recreates the child and this forces the animation that was previously set up, without even calling setupFragmentTransactionAnimation() again, to give me a chance to disable or change the animation. This is my guess of what's happening, at least.
To reproduce this, simply add any animation to the TabContainerFragment's Navigator. Then navigate inside a tab, and then between tabs.

Am I misusing the library, or is this a bug ? Could we have a method that is always called when a transaction will happen ?

Thanks !

**Comment by Lex1717** [comment]
@yurimachioni Hi!
Recently I ran into the same problem. Did you find any solution?

**Comment by yurimachioni** [comment]
Hi!
I didn't. I disabled the animations for now.
The project i'm using this in has really tight deadlines so I can't really spend any time looking inside the lib, maybe there is an easy fix.

**Comment by terrakok** [comment]
Animations between fragments is big pain point.
I recommend not use fragment manager for complex animation cases.
You can use MotionLayout or move views manually
