### ISSUE TITLE
Get current fragment

### ISSUE THREAD

**Issue by azurh** [terrakok/Cicerone#65]
Hello,

Is there a listener/callback which can be attached to Cicerone, which would trigger when there was a screen change?

If not, is there a method which will return the current visible screen, or the backstack?

**Comment by terrakok** [comment]
Cicerone isn't only fragments navigation (or Activities). You can listen backstack with backstackListener and get current fragment by container ID

**Comment by azurh** [comment]
@terrakok did you mean the `OnBackStackChangedListener` found in `android.support.v4.app.FragmentManager`

**Comment by terrakok** [comment]
Yes

**Comment by azurh** [comment]
I thought that I wouldn't have to touch anything regarding Fragments (directly from the Android SDK) ever again, with Cicerone.

That would be a nice convenience method.

Nevermind, thanks.
