### ISSUE TITLE
How should I use overridePendingTransition() method when navigate within activity

### ISSUE THREAD

**Issue by TaxistSamael** [terrakok/Cicerone#66]
Just want to set animation between activities. Could you please help with this?

**Comment by terrakok** [comment]
You can setup animation between activities via Intent parameters

**Comment by TaxistSamael** [comment]
Do you mean, I can't override some method in navigator (or something) to do animations in a way that I used to?

Sorry for disturbing, just interesting:)

**Comment by TaxistSamael** [comment]
Already tried ActivityOptions. Same stuff. Thank you for the answer:)

**Comment by terrakok** [comment]
You need override `createStartActivityOptions` for navigator
