### ISSUE TITLE
sendResult without exit

### ISSUE THREAD

**Issue by Xset-s** [terrakok/Cicerone#71]
Please, implement sendResult without exit.
Smth like: `router.sendResult(code, object)` (now this method is protected 🌵)

**Comment by terrakok** [comment]
No. Because you'll start use the library as data bus but it is navigation tool

**Comment by terrakok** [comment]
I think to remove result callbacks from library.
Data transferring is not navigation responsibility

**Comment by Fi5t** [comment]
@Xset-s try something like this

```kotlin
class YourRouter : Router() {
    public override fun sendResult(resultCode: Int, result: Any?): Boolean {
        return super.sendResult(resultCode, result)
    }
}
```

Enjoy ;)

**Comment by terrakok** [comment]
New version of Cicerone is here! 🔥
