### ISSUE TITLE
MinSdk

### ISSUE THREAD

**Issue by WINTEX** [terrakok/Cicerone#74]
Cicerone min sdk is 19, like in sample app, or previous APIs also compatible? 
Also how do you use showSystemMessage for everything else except toasts? Overriding?

**Comment by badadin** [comment]
> Cicerone min sdk is 19, like in sample app, or previous APIs also compatible?

I use it in my project with min api level 16 and everything is ok

**Comment by WINTEX** [comment]
Yep, today I tested all APIs, API 15 crashes, from API 16 everything OK. But the question about Snackbars is still important, readme says systemMessage works with all types of systemmessages, but I had not found any except toasts

**Comment by terrakok** [comment]
Lates version doesn't support messages
