### ISSUE TITLE
Check current screen is root.

### ISSUE THREAD

**Issue by gigacoderr** [terrakok/Cicerone#76]
Hi!
Thank you for good tool.
It would be so good to add "to the box" function to check, if current screen is root.
At now I'm extending Support(App|Fragment)Navigator with function "isRootScreen". I think, it is useful function.

**Comment by ofdrykkja** [comment]
@gigacoderr can you show me your extension function?

**Comment by AlexanderShniperson** [comment]
voted for this because then we can check this variable and show/hide back buton at ActionBar

**Comment by AlexanderShniperson** [comment]
also: AppNavigator and SupportAppNavigator should have listeners to let us know when activity/frame is actually changed

**Comment by terrakok** [comment]
Hi everyone!
Cicerone philosophy is divide navigation logic and screen switching implementation.
Hence if you need current navigation state in your logic then you can subscribe on fragment manager and provide it anywhere (but you need to remember about its asynchrony)
