### ISSUE TITLE
Will it work with activities?

### ISSUE THREAD

**Issue by lectricas** [terrakok/Cicerone#8]
Do you have any examples of working with activities or this lib is suitable only to work with fragments?

**Comment by terrakok** [comment]
Yes. It works with Activities, Fragments and Views in the same way. But after switching the activity,  the Navigator for application Router will be switched too.
I'll update sample app for this case.

**Comment by terrakok** [comment]
Look it here: [StartActivity.java](https://github.com/terrakok/Cicerone/blob/develop/sample/src/main/java/ru/terrakok/cicerone/sample/ui/start/StartActivity.java)
