### ISSUE TITLE
How to transist complex data between views?

### ISSUE THREAD

**Issue by LAHomieJob** [terrakok/Cicerone#80]
I've seen in your library that you pass data between views with Object data parametr? Could you give me advice how to pass complex data? For example, I want to pass one Integer and one String, what I need to do?

**Comment by terrakok** [comment]
Create class with two fields and pass it as data.

**Comment by terrakok** [comment]
Or use `Pair`

**Comment by LAHomieJob** [comment]
This class-helper should be Parcelable?

**Comment by terrakok** [comment]
You can look on develop branch (new sample inside 😉 )

**Comment by terrakok** [comment]
New version Cicerone (4.0.0) provide Screen class for this.
