### ISSUE TITLE
Support for androidX packages

### ISSUE THREAD

**Issue by amitav13** [terrakok/Cicerone#81]
This library would need to update references:
`android.support.v4.app.Fragment` to `androidx.fragment.app.Fragment`
`android.support.v4.app.FragmentActivity` to `androidx.fragment.app.FragmentActivity`

among others, to support migrations to androidX packages. 

Edit: To be clear, it does currently work with jetifier, but throws up error-level warnings in studio, which always has me checking back to classes to make sure I haven't messed something up.

Maybe we could do another artifact for this, for the sake of compatibility for those who haven't yet updated?

**Comment by maxlord** [comment]
Opened PR: https://github.com/terrakok/Cicerone/pull/88

**Comment by terrakok** [comment]
Develop branch was updated. It will be released in 5.0 version

**Comment by amitav13** [comment]
Any ETA for the release?

**Comment by victorlapin** [comment]
As a temp workaround, you can use these: https://gitlab.com/victorlapin/flasher/tree/master/src/ru/terrakok/cicerone/androidx
