### ISSUE TITLE
How to make transition from one activity to another with Parcelable object?

### ISSUE THREAD

**Issue by LAHomieJob** [terrakok/Cicerone#87]
In my app I make transitions between activities with the help of Cicerone library. The code of my activity is https://gist.github.com/LAHomieJob/d786355666795a8f58b8e7975d302e49#file-choosecallactivity-kt-L152
I want to pass intent with "phoneCallRepresentation" parcelable object, which will be known only during runtime (it depends on selection from recyclerView). I don't know how to do it. Do I need to write putExtra to intent? Or I need to pass this object only in router.navigateTo() as a parameter?

**Comment by terrakok** [comment]
If you use latest version Cicerone then you have to put your parameters to Screen object (like there https://github.com/terrakok/Cicerone/blob/develop/sample/src/main/java/ru/terrakok/cicerone/sample/mvp/main/SamplePresenter.java#L42) and use it for create your `Intent`.

If you use previous version then you have to send your parameters to `Router.navigateTo` method (https://github.com/terrakok/Cicerone/blob/v3.0.0/library/src/main/java/ru/terrakok/cicerone/Router.java#L82) and get it from Forward command inside navigator (like there https://github.com/terrakok/Cicerone/blob/v3.0.0/library/src/main/java/ru/terrakok/cicerone/android/AppNavigator.java#L54)

**Comment by LAHomieJob** [comment]
It has been worked finely. You can close this issue
