### ISSUE TITLE
Add lifecycle aware navigation holder

### ISSUE THREAD

**Issue by OlegSheliakin** [terrakok/Cicerone#93]
Hi everyone! I have an idea to add lifecycle components to Cicerone.

For now, we need to set and remove navigator in lifecycle methods of activity/fragment. For example

```
   @Override
    protected void onResume() {
        super.onResume();
        navigatorHolder.setNavigator(navigator);
    }

    @Override
    protected void onPause() {
        navigatorHolder.removeNavigator();
        super.onPause();
    }
``` 

I think, it would be interesting to have lifecycle aware NavigatorHolder.

Here you will find my sample: [LifeCycleAwareNavigatorHolder](https://gist.github.com/OlegSheliakin/ad62e7d920c99f8ad63a6a60ebb7957f)

**Comment by terrakok** [comment]
I think that is good idea but not for main library. Special module maybe?  
As I see, it's one simple class :) Everyone can copy it to himself project

**Comment by victorlapin** [comment]
@OlegSheliakin many thanks for the sample, nice idea

**Comment by OlegSheliakin** [comment]
> @OlegSheliakin many thanks for the sample, nice idea

You are welcome!
