### ISSUE TITLE
Router#navigateTo() overrides root screen

### ISSUE THREAD

**Issue by Buckstabue** [terrakok/Cicerone#94]
I have a single-activity application and faced with a bug. Steps to reproduce  
1. router.newRootScreen(UserListScreen())  
2. router.navigateTo(UserDetailsScreen())  

Result: UserDetailsScreen becomes a root screen and if I call router.exit(), application is terminated.  
Expected: calling router.exit() gets back to UserListScreen

**Comment by robertBadamshin** [comment]
I have found the same problem

**Comment by terrakok** [comment]
Can you give me more information or sample code? With patch to demo app, for example

**Comment by tim4dev** [comment]
here is a similar problem
https://github.com/terrakok/Cicerone/issues/116

**Comment by terrakok** [comment]
In new version you can use `router.navigateTo` with special flag which setup fragment manager behavior (add/replace).
Please check it :)

**Comment by Tynx11** [comment]
Root transactions are not put to backstack. And in this case the library working correct
